-- MODIFIED TABLE

ALTER TABLE workstation
ADD CONSTRAINT idtask_fk FOREIGN KEY (ID_MAINTENANCE) REFERENCES task(ID_TASK);

ALTER TABLE DIRECTORATE
ADD CONSTRAINT iddir_unq UNIQUE (ID_DIRECTORATE);

ALTER TABLE DIRECTORATE
ADD CONSTRAINT iddir_pri PRIMARY KEY (ID_DIRECTORATE);

ALTER TABLE employees
CHANGE COLUMN ID_SUB_DEPARTEMENT ID_DPT2 VARCHAR (7);

ALTER TABLE employees
ADD COLUMN EMAIL VARCHAR (100) NOT NULL DEFAULT '-';

ALTER TABLE task
MODIFY COLUMN ID_TASK varchar (11);

SELECT * FROM division;

UPDATE employees
SET SITE_UNIT = 'VAC'
WHERE SITE_UNIT = 'XXX';

DELETE FROM departement
WHERE ID_DPT1 >= 'DPT0.05';

SELECT * FROM EMPLOYEES
order by SALARY DESC;

SELECT * FROM DIRECTORATE;

TRUNCATE EMPLOYEES;
DROP TABLE sub_departement;
SHOW TABLES;
DESC employees;

SELECT employees.NAME, directorate.ID_DIR, directorate.DIRECTORATE, level.level
FROM employees
LEFT JOIN directorate
ON employees.ID_DIR = directorate.ID_DIR
LEFT JOIN level
ON employees.ID_LEVEL = level.ID_LEVEL
WHERE level.level = 'Supervisor' AND STATUS = 1;



-- MODIFY on TEBLE employees :
TRUNCATE TABLE employees;
ALTER TABLE employees
ADD CONSTRAINT pri_nip PRIMARY KEY (NIP);
-- >Column ID_LEVEL
ALTER TABLE employees
ADD CONSTRAINT fk_level FOREIGN KEY (ID_LEVEL) REFERENCES level(ID_LEVEL);
ALTER TABLE employees
MODIFY COLUMN ID_LEVEL VARCHAR (5) NOT NULL DEFAULT 'L0.00';
-- >Column ID_DIR
ALTER TABLE employees
CHANGE COLUMN ID_DIRECTORATE ID_DIR VARCHAR (7);
ALTER TABLE employees
ADD CONSTRAINT fk_iddir FOREIGN KEY (ID_DIRECTORATE) REFERENCES directorate(ID_DIRECTORATE);
-- >Column ID_DIV
ALTER TABLE employees
CHANGE COLUMN ID_DIVISION ID_DIV VARCHAR (7);
ALTER TABLE employees
ADD CONSTRAINT fk_iddiv FOREIGN KEY (ID_DIV) REFERENCES division(ID_DIV);
-- >Column ID_DPT
ALTER TABLE employees
CHANGE COLUMN ID_DEPARTEMENT ID_DPT VARCHAR (7);
ALTER TABLE employees
ADD CONSTRAINT fk_iddpt FOREIGN KEY (ID_DPT) REFERENCES departement(ID_DPT);
-- >Column ID_SDP
ALTER TABLE employees
CHANGE COLUMN ID_DPT2 ID_SDP VARCHAR (7);
ALTER TABLE employees
ADD CONSTRAINT fk_idsdp FOREIGN KEY (ID_SDP) REFERENCES sub_departement(ID_SDP);
-- >Column SITE_UNIT
UPDATE employees SET SITE_UNIT = 'VAC' WHERE SITE_UNIT = 'XXX';
ALTER TABLE employees
ADD CONSTRAINT fk_site FOREIGN KEY (SITE_UNIT) REFERENCES site(ID_SITE);
-- >Column EMAIL
ALTER TABLE employees
ADD CONSTRAINT fk_email FOREIGN KEY (EMAIL) REFERENCES email(EMAIL);

-- >Delete All Row
TRUNCATE TABLE employees;

-- MODIFY on TEBLE directorate :
ALTER TABLE directorate
CHANGE COLUMN ID_DIRECTORATE ID_DIR VARCHAR (7);

-- MODIFY on TEBLE division :
UPDATE division SET NOTE = 'DONE' WHERE ID_DIV = 'DIV0.01';
DELETE FROM division;
ALTER TABLE division
ADD COLUMN ID_DIR VARCHAR (7) NOT NULL DEFAULT 'DIR0.00' AFTER DIVISION;
ALTER TABLE division
ADD CONSTRAINT fk_iddir_div FOREIGN KEY (ID_DIR) REFERENCES directorate(ID_DIR);

-- MODIFY on TEBLE departement :
DELETE FROM departement;
ALTER TABLE departement
ADD COLUMN ID_DIV VARCHAR (7) NOT NULL DEFAULT 'DIV0.00' AFTER DEPARTEMENT;


-- MODIFY on TEBLE sub_departement :
TRUNCATE TABLE sub_departement;
DELETE from sub_departement;
ALTER TABLE sub_departement
ADD COLUMN ID_DPT VARCHAR (7) NOT NULL DEFAULT 'DIV0.00' AFTER SUB_DEPARTEMENT;
ALTER TABLE sub_departement
ADD CONSTRAINT fk_iddir_sdp FOREIGN KEY (ID_DIR) REFERENCES directorate(ID_DIR);
ALTER TABLE sub_departement
ADD CONSTRAINT fk_iddiv_sdp FOREIGN KEY (ID_DIV) REFERENCES division(ID_DIV);
ALTER TABLE sub_departement
ADD CONSTRAINT fk_iddpt_sdp FOREIGN KEY (ID_DPT) REFERENCES departement(ID_DPT);

-- MODIFY on TEBLE email :
ALTER TABLE email
ADD CONSTRAINT fk_email_email FOREIGN KEY (PIC_NIP) REFERENCES employees(NIP);